drop table if exists t_user;
 

/*create table t_user (
	id bigint generated by default as identity,
	username varchar(64) not null unique,
	password varchar(255) not null,
	primary key (id)
); */

CREATE TABLE t_user
(
    id int PRIMARY KEY auto_increment ,
    username varchar (30) NOT NULL,
    password varchar(30) NOT NULL
);